class CreatePostConsts:
    CREATE_POST_INPUT_FIELD_XPATH = './/div[@class="x1o1ewxj x3x9cwd x1e5q0jg x13rtm0m x1ey2m1c xds687c \
        xg01cxk x47corl x10l6tqk x17qophe x13vifvy x1ebt8du x19991ni x1dhq9h x1wpzbip"]'
    LIVE_VIDEO_BUTTON_XPATH = './/span[text()="Live video"]'
    PHOTO_VIDEO_BUTTON_XPATH = './/span[text()="Photo/video"]'
    FEELING_ACTIVITY_BUTTON_XPATH = './/span[text()="Feeling/activity"]'
    CREATE_POST_INPUT_FIELD = './/p'
    ADD_PHOTO_VIDEO_TO_POST_INSIDE_THE_POST_BUTTON_XPATH = './/div[@aria-label="Photo/Video"]'
    TAG_PEOPLE_INSIDE_THE_POST_BUTTON_XPATH = './/div[@aria-label="Tag people"]'
    ADD_FEELING_ACTIVITY_INSIDE_THE_POST_BUTTON_XPATH = './/div[@aria-label="Feeling/activity"]'
    ADD_CHECK_IN_INSIDE_THE_POST_BUTTON_XPATH = './/div[@aria-label="Check in"]'
    ADD_LIFE_EVENT_INSIDE_THE_POST_BUTTON_XPATH = './/div[@aria-label="Life event"]'
    CREATE_POST_BUTTON = './/div[@aria-label="Post" and @role="button"]'
    VERIFY_CREATED_POST_XPATH = './/div[@class="xdj266r x11i5rnm xat24cr x1mh8g0r x1vvkbs"]'
    VERIFY_CREATED_POST_TEXT = '"{message_text}"'
    LIKE_POST_BUTTON_XPATH = './/span[text()="Like"]'
    COMMENT_POST_BUTTON_XPATH = './/span[text()="Comment"]'
    SHARE_POST_BUTTON_XPATH = './/span[text()="Share"]'
    HAPPY_SMILE_FEELING_XPATH = './/div[@aria-label="happy"]'

